### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by abunour22** [chadicus/slim-oauth2#6]
When i tried to Curl Authorization

AS you mentionded in Readme with changing in access code sure

curl -H 'Authorization: Bearer c859d2c9eec4800a6277671eba72a5a6f54f8693' http://localhost:8888/books

it returns , 
401 Unauthorized

![ffff](https://cloud.githubusercontent.com/assets/5248013/11739946/1524ac42-9fe7-11e5-8e8e-997e98986f4b.PNG)

**Comment by chadicus** [comment]
In issue #5 you mentioned mysqli storage. Are you using the given mongo example or a mysql implementation?

**Comment by abunour22** [comment]
Am using Pdo ..

**Comment by chadicus** [comment]
Without seeing the code, I can only conclude that there is an issue with your storage implementation.  If you can send me any code samples it would help tremendously.

**Comment by abunour22** [comment]
This is Pdo implementation i used .. 

https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/Storage/Pdo.php

use Chadicus\Slim\OAuth2\Routes;
use Chadicus\Slim\OAuth2\Middleware;
use Slim\Slim;
use OAuth2\Server;
use OAuth2\Storage;
use OAuth2\GrantType;

/*
|--------------------------------------------------------------------------
| Start Slim Application
|--------------------------------------------------------------------------
 */
$app = new Slim(array(
    'debug'              => true,
    'mode'               => 'development',
    'cookies.secret_key' => 'sercret',
    'templates.path'     => dirname(dirname(**FILE**)) . '/private/vendor/chadicus/slim-oauth2-routes/templates'
));

$app->config('whoops.editor', 'sublime');
$app->add(new \Zeuxisoo\Whoops\Provider\Slim\WhoopsMiddleware);

/*
|--------------------------------------------------------------------------
| Json Api View
|--------------------------------------------------------------------------
|
| Make Api Results At Json View
|
 */
$app->view(new \JsonApiView());
$app->add(new \JsonApiMiddleware());

/*
|--------------------------------------------------------------------------
| Init Connection Data
|--------------------------------------------------------------------------
 */
$connection = array(
    'dsh'      => FD_DATABASE_HOST,
    'dsn'      => FD_DATABASE_NAME,
    'username' => FD_DATABASE_USER,
    'password' => FD_DATABASE_PASS,
);

/*
|--------------------------------------------------------------------------
| Prepare Authorization Storage
|--------------------------------------------------------------------------
 */
$storage = new Storage\Pdo($connection);

$server = new Server(
    $storage,
    [
        'access_lifetime' => 3600
    ],
    [
        new GrantType\ClientCredentials($storage),
        new GrantType\AuthorizationCode($storage)
    ]
);

/*
|--------------------------------------------------------------------------
| Prepare Routes Of Authorization , Token , Code
|--------------------------------------------------------------------------
 */
Routes\Token::register($app, $server);
Routes\Authorize::register($app, $server);
Routes\ReceiveCode::register($app);

/*
|--------------------------------------------------------------------------
| Prepare Authorization Middleware
|--------------------------------------------------------------------------
 */
$authorization = new Middleware\Authorization($server);
$authorization->setApplication($app);

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
 */
            $app->post('/books', $authorization, function () use ($app) {
                $app->render(200, array(
                    'error' => false,
                    'msg'   => "Welcome!"
                ));
            });

/*
|--------------------------------------------------------------------------
| Run Application
|--------------------------------------------------------------------------
 */
$app->run();

**Comment by hellracer** [comment]
For anyone who stumble the same issue I was able to solved the problem by adding the following code to .htaccess

RewriteRule .\* - [env=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

PHP can't fetch Authorization Bearer header without adding this on my htaccess results to 401

**Comment by chadicus** [comment]
I'm not entirely sure, but this issue may have been resolved with this [bug fix](https://github.com/chadicus/slim-oauth2-http/pull/22) in the http package

**Comment by hellracer** [comment]
Hi chadicus,

Yes i'm pretty sure this was the case, I remove that particular RewriteRule and it didn't work

please see command transcript

[root@dbmaster api]#  curl -H 'Authorization: Bearer 6d6638f4ffadd348a3a57080b0a1faa88feac72b' http://localhost/transaction/CB-MKT/1000-2323-213/100000/0/0 -X GET -vvv
- About to connect() to localhost port 80 (#0)
-   Trying ::1... connected
- Connected to localhost (::1) port 80 (#0)
  > GET /transaction/CB-MKT/1000-2323-213/100000/0/0 HTTP/1.1
  > User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.19.1 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
  > Host: localhost
  > Accept: _/_
  > Authorization: Bearer 6d6638f4ffadd348a3a57080b0a1faa88feac72b
  > 
  < HTTP/1.1 401 Unauthorized
  < Date: Fri, 14 Oct 2016 10:08:51 GMT
  < Server: Apache/2.2.15 (CentOS)
  < X-Powered-By: PHP/5.6.26
  < Set-Cookie: PHPSESSID=vio4er6bq6t68ckcfkmut82314; path=/
  < Expires: Thu, 19 Nov 1981 08:52:00 GMT
  < Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
  < Pragma: no-cache
  < WWW-Authenticate: Bearer realm="Service"
  < Content-Length: 0
  < Connection: close
  < Content-Type: 
  < 
- Closing connection #0
  [root@dbmaster api]# vi .htaccess 
  [root@dbmaster api]#  curl -H 'Authorization: Bearer 6d6638f4ffadd348a3a57080b0a1faa88feac72b' http://localhost/transaction/CB-MKT/1000-2323-213/100000/0/0 -X GET -vvv
- About to connect() to localhost port 80 (#0)
-   Trying ::1... connected
- Connected to localhost (::1) port 80 (#0)
  > GET /transaction/CB-MKT/1000-2323-213/100000/0/0 HTTP/1.1
  > User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.19.1 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
  > Host: localhost
  > Accept: _/_
  > Authorization: Bearer 6d6638f4ffadd348a3a57080b0a1faa88feac72b
  > 
  < HTTP/1.1 200 OK
  < Date: Fri, 14 Oct 2016 10:08:59 GMT
  < Server: Apache/2.2.15 (CentOS)
  < X-Powered-By: PHP/5.6.26
  < Set-Cookie: PHPSESSID=esnqrnb8juden17qhe0cs4taf0; path=/
  < Expires: Thu, 19 Nov 1981 08:52:00 GMT
  < Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
  < Pragma: no-cache
  < Content-Length: 173
  < Connection: close
  < Content-Type: application/json;charset=utf-8
  < 
- Closing connection #0
  {"status":200,"transactionId":1,"origin":"CB-MKT","destination":"BDO-MKT","postedOn":"10\/14\/2016 06:08:59 PM","accountNo":"1000-2323-213","amount":100000,"type":"Deposit"}[root@dbmaster api]

**Comment by hellracer** [comment]
Please see my composer.json if this would help to track down the issue.

[root@dbmaster api]# cat composer.json 
{
    "require": {
        "slim/slim": "^3.5",
        "slim/csrf": "^0.7.0",
        "chadicus/slim-oauth2": "^3.0",
        "slim/views": "^0.1.3",
        "slim/http": "^0.1.0",
        "slim/php-view": "^2.2"
    }
}

**Comment by chadicus** [comment]
@hellracer thanks for the info, i'll try to look into this over the weekend.

**Comment by chadicus** [comment]
@hellracer  The issue exists with your use of `slim/http 0.1.0`  In that library [Headers::createFromEnvironment](https://github.com/slimphp/Slim-Http/blob/0.1.0/src/Headers.php#L48) method does not contain the special case for the `Authorization` header found in the [Headers::createFromEnviornment](https://github.com/slimphp/Slim/blob/3.x/Slim/Http/Headers.php#L54) method in the base `slim` library. By including the `slim/http` package you are overriding the base class.  

I can't offer a solution other than keep your RewriteRule or remove the `slim/http` dependency

**Comment by tsmgeek** [comment]
This has happened with me on Slim3 without the dependency you mentioned.
Added rewrite rule and all was good again.
