### ISSUE TITLE
The grant type was not specified in the request

### ISSUE THREAD

**Issue by arnokoehler** [chadicus/slim-oauth2#7]
Hi, 

I am trying to figure out your setup - it looks awesome; but I am overseeing something!
The thing I am stuck on is:

{
"error": "invalid_request"
"error_description": "The grant type was not specified in the request"
}

When calling:
http://localhost/cheapp/index.php/token
from the advanced rest client with payload:
client_id=librarian&client_secret=secret&grant_type=client_credentials
and header:
Accept: application/json

It keeps throwing that nasty:
"error": "invalid_request"

probably had something to do with my setup .. database creation was not done by running some script but by finding the create tables in the code and running them. Should I have used composer for this in some way? Could only find some test code that hit this - so how does this work?

**Comment by yeco** [comment]
I'm having the exact same issue and I installed everything using composer.

**Comment by arnokoehler** [comment]
You might have an issue with the oauth header - the auth variable is killed by php, that is something that you have to fix when setting up your SLIM api.

**Comment by arnokoehler** [comment]
$this->headers['Authorization'] this one is not there in the code until you fix something with the AUTHORIZATION header like this in .htacces

  RewriteEngine On
    RewriteRule .\* - [env=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [QSA,L]

**Comment by chadicus** [comment]
Actually, if it is indeed the `HTTP_AUTHORIZATION` header issue, there is a fix for that in v3.  I can do a    backport of the fix for v1 if needed.

**Comment by chadicus** [comment]
Released #9 in v1.0.1 which contains the same fix for the HTTP_AUTHORIZATION issue as in v3.

**Comment by yeco** [comment]
Weird, still not working... The interesting part is that if I do it with curl it works fine.
`curl -X POST -d client_id=client -d client_secret=secret -d grant_type=client_credentials http://localhost/api/token`

But if I send the same params in a querystring in a POST it doesn't.
`http://localhost/api/token?client_id=client&client_secret=secret&grant_type=client_credentials`

Am I missing something?

**Comment by chadicus** [comment]
I think the underlying oauth2 server ignores the query parameters when the request is a POST.  Use something like [Postman](https://chrome.google.com/webstore/detail/postman-rest-client-short/mkhojklkhkdaghjjfdnphfphiaiohkef?hl=en) and try sending the parameters in the body of the request.

**Comment by chadicus** [comment]
@yeco are you still having the issue? If so are you using `slim/http` in your composer.json?

**Comment by yeco** [comment]
Not anymore, please close the issue. Thanks!
